# Generated by Django 4.2.8 on 2024-01-10 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enquiry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='enquiry',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='approval',
        ),
        migrations.AddField(
            model_name='design',
            name='approval',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Reject', 'Reject')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='design',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
